[FEATURE] Permettre de rendre Pix Input et Pix Input Password obligatoires (PIX-4138).
1024pix/pix-ui pull request #204
Opened 2022-02-28 14:26 UTC by AndreiaPena

## :boom: BREAKING_CHANGES
Pas de BREAKING_CHANGES ici.

## :christmas_tree: Problème
Aujourd'hui si on a un besoin de mettre nos deux composants, Pix Input et Pix Input Password, en obligatoire, on doit faire une bidouille dans nos apps ( ne pas mettre le label du composant pour mettre un label et un abbr à la main) 

## :gift: Solution
Permettre de rendre le composant obligatoire. 
Ici on attend du texte pour le besoin de traduction. (et non un booléen)

## :santa: Pour tester
Aller sur Storybook et voir les deux composants.
Vérifier visuellement le rendu, ouvrir la console et voir que les inputs sont en required et aria-required.

2022-02-28 14:27 UTC, pix-service commented
I'm deploying this PR to:

- Storybook: https://ui-pr204.review.pix.fr

 Please check it out!

2022-03-01 09:26 UTC, yschoueri approved these changes

2022-03-01 11:07 UTC, Anne-Gaelle-S commented on tests/integration/components/pix-input-password-test.js
> +  test.only('it should be possible to make pix input password required', async function (assert) {
😱  !!!

2022-03-01 11:11 UTC, Anne-Gaelle-S reviewed
Je sais pas si c'est un bug, sur storybook quand je joue avec la propriété "requiredLabel" j'ai le composant HTML qui a le required vide : 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/38167520/156158826-d7624adb-d29e-41b0-b0ae-c1e5bce05685.png">

2022-03-01 11:11 UTC, Anne-Gaelle-S commented on tests/integration/components/pix-input-password-test.js
> +  test.only('it should be possible to make pix input password required', async function (assert) {
```suggestion
  test('it should be possible to make pix input password required', async function (assert) {
```

2022-03-01 11:12 UTC, Anne-Gaelle-S requested changes
Ne pas merger sans enlever le .only qui traine !

2022-03-01 11:13 UTC, Anne-Gaelle-S commented
Suggestion : 
Est-ce qu'on pourrait rajouter un input required dans le formulaire d'exemple de storybook ? Pour voir comme ça se comporte dans un vrai formulaire ? :)

2022-03-01 13:23 UTC, iwazaru approved these changes

2022-03-01 13:23 UTC, clemlatz commented on addon/components/pix-input.hbs
> +        <abbr title={{@requiredLabel}} class="mandatory-mark" aria-hidden="true">*</abbr>
**question**
Top, je n'avais jamais pensé à utiliser `abbr` pour ça. 
Du coup ici le `title` fait office de libellé accessible ?

2022-03-01 13:23 UTC, iwazaru commented on tests/integration/components/pix-input-password-test.js
> +    assert.dom(screen.getByLabelText('* Mot de passe')).exists();
**suggestion** pour utiliser qunit et la testing-library : 

```suggestion
    const requiredPasswordInput = screen.getByLabelText('* Mot de passe');
    assert.dom(requiredPasswordInput).isRequired();
```

2022-03-02 13:17 UTC, AndreiaPena commented on tests/integration/components/pix-input-password-test.js
> +  test.only('it should be possible to make pix input password required', async function (assert) {
ouuuuups

2022-03-02 13:18 UTC, AndreiaPena commented
> Je sais pas si c'est un bug, sur storybook quand je joue avec la propriété "requiredLabel" j'ai le composant HTML qui a le required vide : <img alt="image" width="730" src="https://user-images.githubusercontent.com/38167520/156158826-d7624adb-d29e-41b0-b0ae-c1e5bce05685.png">

ah intéressant c'est le comportement sur firefox ça, coté google c'est bon pourtant :o

2022-03-02 13:18 UTC, AndreiaPena commented on tests/integration/components/pix-input-password-test.js
> +    assert.dom(screen.getByLabelText('* Mot de passe')).exists();
cool je prend !

2022-03-02 13:18 UTC, AndreiaPena commented on addon/components/pix-input.hbs
> +        <abbr title={{@requiredLabel}} class="mandatory-mark" aria-hidden="true">*</abbr>
tout à fait :)

2022-03-02 13:19 UTC, AndreiaPena commented
> Suggestion : Est-ce qu'on pourrait rajouter un input required dans le formulaire d'exemple de storybook ? Pour voir comme ça se comporte dans un vrai formulaire ? :)

ça va pas faire trop avec les versions classiques ?

2022-03-02 14:19 UTC, Anne-Gaelle-S approved these changes

2022-04-11 08:25 UTC, merged