[TECH] Améliorer l'expérience de dev
1024pix/pix-ui pull request #354
Opened 2023-03-06 13:22 UTC by yannbertrand

## :christmas_tree: Problème
- Une dépréciation Storybook concernant le dossier static que nous utilisons est renvoyée
- On lance un serveur de dev Ember sur le port 4200 sans qu'on ne l'utilise derrière

## :gift: Solution
- Ne plus utiliser le paramètre `--static-dist`/`-s` et préférer remplir le champ `staticDirs` dans le `.storybook/main.js`.
- Utiliser `$ ember build --watch` plutôt que `$ ember serve`.

## :star2: Remarques
RAS

## :santa: Pour tester
Tirer la branche en local, vérifier que `npm run storybook` fonctionne toujours (lancement de Storybook, les stories sont bien accessibles, le hot reload fonctionne...), y compris après un `npm run clean`.

2023-03-06 13:31 UTC, VincentHardouin commented on package.json
> +    "serve-ember": "ember build --watch",
Si je comprends bien, on n'aura plus accès au port 4200 et donc on ne pourra plus lancer les tests dans le navigateur avec le workflow classique : 

```
npm run serve-storybook
```

Puis `http://localhost:4200/tests` quand on le souhaite.

2023-03-06 13:37 UTC, yannbertrand commented on package.json
> +    "serve-ember": "ember build --watch",
J'avoue que je ne me rappelle pas avoir lancé les tests Pix UI #ShameOnMe... Je revert ce commit puisque ça semble utile !

2023-04-14 11:35 UTC, octo-topi requested changes
`npm ci` échoue en local :thinking: mais pas en CI
```

npm ERR! Invalid Version: 3.5.0pr2

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/topi/.npm/_logs/2023-04-14T11_33_54_115Z-debug-0.log

3802 verbose unfinished npm timer metavuln:calculate:security-advisory:yui:BFji23dRqpNDTDt0PtAbs39ndHG4jIMV7Eu5lN+70e8OMGQebMyarAOHX0I4auPW1IGsxAq407Ifu+RBACRs9g== 1681472061661
3803 verbose unfinished npm timer metavuln:load:security-advisory:yui:BFji23dRqpNDTDt0PtAbs39ndHG4jIMV7Eu5lN+70e8OMGQebMyarAOHX0I4auPW1IGsxAq407Ifu+RBACRs9g== 1681472061792
3804 verbose code 1
3805 error A complete log of this run can be found in:
3805 error     /home/topi/.npm/_logs/2023-04-14T11_33_54_115Z-debug-0.log

```

2023-04-14 12:23 UTC, octo-topi approved these changes
Story est utilisable
![image](https://user-images.githubusercontent.com/56302715/232041827-01b8f090-c071-4c50-b664-ac2d28156d02.png)

Plus de warning de deprecation
![image](https://user-images.githubusercontent.com/56302715/232042327-3d3c33c5-79e2-405d-b3e9-5e936bd454ea.png)

2023-05-03 10:11 UTC, merged