[TECH] Ajouter la compatibilité avec node18
1024pix/pix-ui pull request #383
Opened 2023-04-11 13:54 UTC by mickaelalibert

## :boom: BREAKING_CHANGES
> _Décrivez ici les changements cassant (voir la doc associée)[https://github.com/1024pix/pix-ui/blob/dev/docs/breaking-changes.stories.mdx], s'il n'y en a pas indiquez le aussi.

## :christmas_tree: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :gift: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :star2: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :santa: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-04-14 11:29 UTC, octo-topi approved these changes

2023-04-14 11:29 UTC, octo-topi requested changes, later dismissed
Le déploiement échoue sur
```
       - Dangerous semver range (>) in engines.node
         https://doc.scalingo.com/languages/javascript/nodejs#specifying-a-nodejs-version
```

Quel est le besoin de supporter node v16 et v18 ?

2023-04-14 12:09 UTC, francois2metz commented
> Quel est le besoin de supporter node v16 et v18 ?
Cela permet de mettre a jour pix-ui sur les applis front sans devoir synchroniser la mise à jour vers node 18 même temps.

2023-07-25 08:48 UTC, francois2metz approved these changes
:rose: :hibiscus: :white_flower: :wilted_flower:  :tulip: :sunflower: :cherry_blossom:  LGTM :cherry_blossom: :sunflower:  :tulip: :wilted_flower: :white_flower: :hibiscus: :rose:

2023-07-25 09:08 UTC, merged