[FEATURE] Modification des addons dépréciés
1024pix/pix-ui pull request #55
Opened 2020-12-14 08:41 UTC by bpetetot

## :unicorn: Description du composant

Certains addons sont dépréciés par Storybook en faveur de nouveaux:
- Addon Notes remplacé par Addon Docs
- Addon Knobs remplacé par Addon Control

Dans cette PR, nous testons ces nouveaux addon et comment les intégré (sur le composant pix-stars).
Nous avons testé l'utilisation du MDX pour Docs.

Il sera nécessaire de revoir les blueprints pour la génération de composants pix.

2020-12-14 10:56 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +import { hbs } from 'ember-cli-htmlbars';
Cet import peut être supprimé

2020-12-14 10:56 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +import { withKnobs, number, select, text } from '@storybook/addon-knobs';
Ces imports peuvent être supprimé

2020-12-14 10:57 UTC, bpetetot commented on addon/stories/pix-stars.stories.mdx
> +import * as stories from './pix-stars.js';
Pourquoi enlever le `.stories` ? car ce fichier contient bien les stories du composant.

2020-12-14 10:58 UTC, bpetetot commented on addon/stories/pix-stars.stories.mdx
>  import { hbs } from 'ember-cli-htmlbars';
J'ai oublié de supprimer cet import :P, il n'est plus utilisé

2020-12-14 10:59 UTC, bpetetot commented on addon/stories/pix-stars.stories.mdx
>  import { withKnobs, number, select, text } from '@storybook/addon-knobs';
J'ai oublié de supprimer ces imports :P, ils ne sont plus utilisés

2020-12-14 11:01 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.js
> +export const stars = (args) => {
Il faut mettre le nom du composant ici:
```suggestion
export const <%= classifiedModuleName %> = (args) => {
```

2020-12-14 11:01 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +  <Story name='Pix<%= classifiedModuleName %>' story={stories.stars} height="60px" />
Il faut mettre le nom du composant ici, c'est celui qui est exporté dans le fichier des stories.
```suggestion
  <Story name='Pix<%= classifiedModuleName %>' story={stories.<%= classifiedModuleName %>} height="60px" />
```

2020-12-14 11:12 UTC, celineung commented on addon/stories/pix-stars.stories.mdx
> +import * as stories from './pix-stars.js';
La story est désormais dans `pix-stars.stories.mdx`. Cela me semble bizarre d'avoir deux fichiers stories pour le même composant.
Le fichier `pix-stars.stories.js` n'exporte que deux variables qui vont être utilisés par `pix-stars.stories.mdx`, donc je trouve que ce n'est pas une story.
Est-ce que tu préfères toujours garder le `.stories.js` en plus du .stories.mdx ?

2020-12-14 11:14 UTC, celineung commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +  <Story name='Pix<%= classifiedModuleName %>' story={stories.stars} height="60px" />
oups ^^

2020-12-17 08:51 UTC, xav-car approved these changes

2020-12-17 08:57 UTC, jonasgrilleres commented on .storybook/main.js
> +  stories: ['../addon/**/*.stories.@(js|mdx)'],
Trop cool si ça supporte les stories MDX

2020-12-17 09:06 UTC, jbuget requested changes

2020-12-17 09:06 UTC, jbuget commented on .storybook/preview.js
> +  viewMode: 'docs', // set docs tab by default
Je suis pas un grand fan de ce (type de) commentaire. Je préconise plutôt de l'inclure dans la description du commit associé, afin que la ligne de code soit à jamais synchronisé avec le commentaire et l'explication.

2020-12-17 09:06 UTC, jbuget commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.js
> +// TODO: add component attributes information
Y a vraiment pas moyen de prendre la demi-heure (ou plus si nécessaire) pour éviter ce `TODO` ?

2020-12-17 09:06 UTC, jbuget commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +TODO: insert component description
On est d'accord que ce `// TODO` là est tout à fait normal et fait partie du _scaffolding_ ou alors j'ai mal compris et c'est une coquille ?

2020-12-17 09:11 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.js
> +// TODO: add component attributes information
Il s'agit d'un TODO dans le _scaffolding_ d'un composant qui permet de décrire les arguments du composant.
Quand le/la dev génèrera un nouveau composant, ce TODO lui indique qu'il y a des modifications à faire ici.

2020-12-17 09:12 UTC, bpetetot commented on blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
> +TODO: insert component description
Oui tu as très bien compris il s'agit d'un TODO dans le scaffolding de la doc du composant.
Ici le/la dev devra insérer la documentation du composant.

2020-12-17 11:34 UTC, jbuget approved these changes

2020-12-17 12:02 UTC, bpetetot commented on .storybook/preview.js
> +  viewMode: 'docs', // set docs tab by default
Done

2020-12-17 12:04 UTC, merged